= RustMsgPack Readme
:author: Skrylar

RustMsgPack is a Rust-native implementation of for the http://msgpack.org/[MsgPack] data serialization format. It aims to provide an elegant, layered and easy to use API.

My implementation supports
https://github.com/msgpack/msgpack/blob/8b3c890a33aa0d235c62d01d4c9fafc6df984d9e/spec.md[everything
in the MsgPack v5 specification proposal]. Using the provided `MsgPackReader` and `MsgPackWriter` structures, you can read and write any arbitrary stream of MsgPack values. When using the reader, a custom enum is provided to interpret the data 'exactly as read from the stream' and the writer will use the most efficient means of packing your data for compactness.

== Todo

 - Complete round-trip unit tests.
 - Trait implementations for Rust's standard library types.
 - Assemble benchmarks of the encoding/decoding process, and compare them to `msgpack-c`.
 - Interoperability tests with messages encoded in other implementations.
 - Make sure everything is properly tagged and documented.
 - Support `Map` types (and Rust's `HashTable` equivalent.) footnote:[I didn't write this because I don't know much about the `HashTable` type.]
 - Zero-copy reader. footnote:[msgpack-c has this; it allows reading strings and binary buffers from a byte buffer we already have, which reduces memory I/O for short-lived information such as command strings.]
 - Support for Rust's built-in serialization traits.

== License

RustMsgPack is provided under the 'zlib' license:

Copyright (c) 2014 Joshua A. Cearley

This software is provided 'as-is', without any express or implied
warranty. In no event will the authors be held liable for any damages
arising from the use of this software.

Permission is granted to anyone to use this software for any purpose,
including commercial applications, and to alter it and redistribute it
freely, subject to the following restrictions:

   1. The origin of this software must not be misrepresented; you must not
   claim that you wrote the original software. If you use this software
   in a product, an acknowledgment in the product documentation would be
   appreciated but is not required.

   2. Altered source versions must be plainly marked as such, and must not be
   misrepresented as being the original software.

   3. This notice may not be removed or altered from any source
   distribution.

== Notes

`doc/spec.md` is not covered under the above license.

